config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :articulos
  resources :articulos

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
    has_many :comentarios
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
    belongs_to :articulo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'AArticulo fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :cuerpo, :fecha)
    end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @articulo = Articulo.find_by_id(params[:articulo_id])
    @comentario = Comentario.new(articulo_id: @articulo.id)
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:autor, :cuerpo, :fecha, :articulo_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/articulos/_form.html.erb
<%= form_for(@articulo) do |f| %>
  <% if @articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
      <% @articulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editar Articulo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @articulo %> |
<%= link_to 'Regresar', articulos_path %>

app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="pos">Listado de Articulos</h1>

<table>
  <thead>
    <tr>
      <th> TITULO </th>
      <th> CUERPO </th>
      <th> FECHA </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.cuerpo %></td>
        <td><%= articulo.fecha %></td>
        <td><%= link_to 'Mostrar', articulo %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
        <td><%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Articulo nuevo', new_articulo_path %>
 
<ul class= "media-list">
  <li class= "media">A
    <ul>
        <li class= "media">MP4 (2Gb)</li>
        <li class= "media">MP4 (4Gb)</li>
        <li class= "media">MP4 (8Gb)</li>
        <li class= "media">MP4 (16Gb)</li>
    </ul>
  </li>
  <li class= "media">B</li>
  <li class= "media">C</li>
  <li class= "media">D</li>
</ul>


<div class="container">
  
  <div class "row">

   <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12 ">
     Un ticket: al enviar la palabra PISTA o cualquier palabra errada o mensaje que no esté configurado como respuesta válida de la promoción.
      </div>
      <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12 ">
    Envía la palabra PISTA al 3939 y recibirás un SMS con las pistas de la palabra clave que debes adivinar. Por cada SMS que envíes acumularás tickets electrónicos para participar en el sorteo de cuatro reproductores MP4 y de un teléfono inteligente.
   </div>
    <div class= "col-lg-4 col-md-6 col-sm-6 col-xs-12 ">
    Cada vez que envíes un SMS contestando una pista, recibirás un mensaje de texto indicando si acertaste la respuesta o no y se te indicarán nuevas pistas dentro del mismo mensaje. La participación será continua hasta tanto tú lo decidas. También podrás responder vía mensaje de texto a las pistas que diariamente se publicarán en la cuenta de Twitter @MovistarVe  
        </div>
   </div>   
  </div>
</div>

app/views/articulos/new.html.erb
<h1>Articulo nuevo</h1>

<%= render 'form' %>

<%= link_to 'Regresar', articulos_path %>

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @articulo.cuerpo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @articulo.fecha %>
</p>

<%= link_to 'Editar', edit_articulo_path(@articulo) %> |
<%= link_to 'Regresar', articulos_path %>

<h2 id="Titulo">Comentarios</h2>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulo.comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Mostrar', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Comentario', new_comentario_path(articulo_id: @articulo.id)%>

<ul class= "media-list">
  <li class= "media">A
    <ul>
        <li class= "media">MP4 (2Gb)</li>
        <li class= "media">MP4 (4Gb)</li>
        <li class= "media">MP4 (8Gb)</li>
        <li class= "media">MP4 (16Gb)</li>
    </ul>
  </li>
  <li class= "media">B</li>
  <li class= "media">C</li>
  <li class= "media">D</li>
</ul>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
 <%= f.hidden_field :articulo_id %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :cuerpo %><br>
    <%= f.text_area :cuerpo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editar Comentario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @comentario %> |
<%= link_to 'Regresar', @comentarios.articulo %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listar Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Cuerpo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.autor %></td>
        <td><%= comentario.cuerpo %></td>
        <td><%= comentario.fecha %></td>
        <td><%= link_to 'Mostrar', comentario %></td>
        <td><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Eliminar', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>Nuevo Comentario</h1>

<%= render 'form' %>

<%= link_to 'Regresar', @comentario.articulo %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comentario.autor %>
</p>

<p>
  <strong>Cuerpo:</strong>
  <%= @comentario.cuerpo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @comentario.fecha %>
</p>

<%= link_to 'Editar', edit_comentario_path(@comentario) %> |
<%= link_to 'Regresar', @comentario.articulo %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<center>Hecho por: Germán A.Maldonado</center>
<center>Contacto: geralma10@gmail.com</center>

</body>
</html>